config/routes.rb
Rails.application.routes.draw do
  get 'eventsvideos/index', as: 'event_video'

  get 'eventspictures/index', as: 'event_pictures'

  root 'listings#index'

  get 'events/:category', to: 'events#index', as: 'events_type'

  get 'event/:category/:id', to: 'events#show', as: 'event'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :category

  def index
    @events = EventsDecorator.new(
      category:    params[:category],
      page:        params[:page],
      max_results: 8
    ).decorated_events

    page = params[:page].to_i >= 1 ? params[:page].to_i : 1

    @page = page

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def show
    @event = EventDecorator.new(one_event)
  end

  private

  def one_event
    EvvntConnector.get_event(params[:id]).body
  end

  def category
    @category = params[:category]
  end
end

app/controllers/eventspictures_controller.rb
class EventspicturesController < ApplicationController
  def index
  end
end

app/controllers/eventsvideos_controller.rb
class EventsvideosController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @events = EventsDecorator.new(max_results: 6).decorated_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active(url)
    "active" if current_page?(url)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/eventspictures_helper.rb
module EventspicturesHelper
end

app/helpers/eventsvideos_helper.rb
module EventsvideosHelper
end

app/views/events/_categories.haml
= @category.upcase
.col-md-offset-1
  %nav.navbar.navbar-light
    %div.nav.navbar-nav
      = link_to events_type_path(category: :arts),
              class:"nav-item nav-link btn #{active(events_type_path(category: :arts))}" do
        %small
          .glyphicon.glyphicon-picture
          Arts
      = link_to events_type_path(category: :music),
              class:"nav-item nav-link btn #{active(events_type_path(category: :music))}" do
        %small
          .glyphicon.glyphicon-music
          Music
      = link_to events_type_path(category: :movies), remote: true,
              class:"nav-item nav-link btn #{active(events_type_path(category: :movies))}" do
        %small
          .glyphicon.glyphicon-film
          Movies
      = link_to events_type_path(category: :nightlife), remote: true,
              class:"nav-item nav-link btn #{active(events_type_path(category: :nightlife))}" do
        %small
          .glyphicon.glyphicon-play-circle
          Nightlife
      = link_to events_type_path(category: "food & drinks"), remote: true,
              class:"nav-item nav-link btn #{active(events_type_path(category: 'food & drinks'))}" do
        %small
          .glyphicon.glyphicon-glass
          Food/Drinks
      = link_to events_type_path(category: :festivals), remote: true,
              class:"nav-item nav-link btn #{active(events_type_path(category: :festivals))}" do
        %small
          .glyphicon.glyphicon-sound-stereo
          Festivals
      = link_to events_type_path(category: :fitness), remote: true,
              class:"nav-item nav-link btn #{active(events_type_path(category: :fitness))}" do
        %small
          .glyphicon.glyphicon-heart
          Fitness
      = link_to events_type_path(category: :gaming), remote: true,
              class:"nav-item nav-link btn #{active(events_type_path(category: :gaming))}" do
        %small
          .glyphicon.glyphicon-queen
          Gaming

app/views/events/_events_list.haml
- if @events
  - @events.each do |event|
    .col-sm-6.event-box
      = link_to "More Details", event_path(id: event.id, category: @category),
              class: "btn-lg btn-more"
      .event-card.well.well-sm
        = image_tag(event.image_url,width: "100%",height: "250px")
        .panel-body
          %h3
            %b= event.title
          %p
            %i.glyphicon.glyphicon-calendar
            = event.starting_at
          %p
            %i.glyphicon.glyphicon-map-marker
            = event.name_of_venue
        .footer
          .col-xs-6.pull-right.text-right
            = link_to "#" do
              = fa_stacked_icon "bookmark", base: "circle"
            = link_to "#" do
              = fa_stacked_icon "share-alt", base: "circle"
- else
  %p.text-center Nothing Found

app/views/events/_next.haml
= link_to events_type_path(category: @category, page: @page + 1), remote: true do
  \&nbsp; Next
  = fa_stacked_icon "chevron-right", base: "square", class: "5px"

app/views/events/_previous.haml
= link_to events_type_path(category: @category, page: @page - 1), remote: true do
  = fa_stacked_icon "chevron-left", base: "square", class: "5px"
  Back &nbsp;

app/views/events/index.haml
.main-layout
  .container-fluid
    %div.loader-bg
      = image_tag '500.gif', class: "loader"
    %h1#category
      = render('layouts/categories_menu')
    .col-md-10
      .row#events
        = render('events/events_list')
      .row
        .footer
          .row.pages
            .col-xs-6.text-right#previous
              = render('events/previous')
            .col-xs-6.text-left#next
              = render('events/next')
    .col-md-2

app/views/events/index.js.haml
$('#events').html("#{escape_javascript(render 'events/events_list')}");

$('#previous').html("#{escape_javascript(render 'events/previous')}");

$('#next').html("#{escape_javascript(render 'events/next')}");

$('#category').html("#{escape_javascript(render 'events/categories')}");

app/views/events/show.haml
- set_meta_tags keywords: @event.keywords
.main-layout
  .container-fluid
    %h1
      = @category.upcase
      = render('layouts/categories_menu')
    .col-md-10
      %h1
        = title @event.title
      .row
        .col-sm-8
          #carousel.carousel.slide{"data-ride" => "carousel"}
            .carousel-inner
              .item.active
                = image_tag(@event.image_url, width: "100%", height: "300px")
                .carousel-caption
                  = @event.summary
              - @event.image_urls.each do |image|
                .item
                  = image_tag(image ,width: "100%",height: "300px")
                  .carousel-caption
                    = @event.summary
            %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel", :role => "button"}
              %span.glyphicon.glyphicon-chevron-left
            %a.right.carousel-control{"data-slide" => "next", :href => "#carousel", :role => "button"}
              %span.glyphicon.glyphicon-chevron-right

          %h3.page-header
          .row.well.well-lg
            %span
              %i.glyphicon.glyphicon-time
              %small #{ @event.starting_at } - #{ @event.ending_at }
            %br
            - @event.prices.each_pair do |description, price|
              %small.col-sm-6
                %b.text-info #{description.titlecase}
                \=> #{price}
            .row
              - unless @event.artists.blank?
                %h5
                  Artists/Guests
                = @event.artists.upcase
          .footer
            - if @event.ticket
              = link_to @event.ticket,target: "_blank",
              class: "btn btn-large btn-success btn-block" do
                .glyphicon.glyphicon-tag
                  Get Your Tickets
          %br
          .row.well.well-lg
            %h3.page-header
              Details
            = @event.description
          %h3.page-header Enquiries
          .row.enquiries.text-center
            .col-sm-3
              %p
                = fa_stacked_icon "user", base: "circle", class: "fa-2x"
              #{@event.contact['name']}
            .col-sm-6
              %p
                = fa_stacked_icon "envelope", base: "circle", class: "fa-2x"
              #{@event.contact['email']}
            .col-sm-3
              %p
                = fa_stacked_icon "phone", base: "circle", class: "fa-2x"
              #{@event.contact['tel']}
        .col-sm-4
          #mapid{ data:{ latitude: @event.venue['latitude'],
          longitude: @event.venue['longitude'] } }
          %br
          %h4.page-header Place
          = @event.complete_venue
    .col-md-2

app/views/eventspictures/index.haml
.main-layout
  %h1.text-center
    Events In Pictures
  .row
    .col-sm-4
      = link_to event_pictures_path do
        .letter
          = image_tag 'http://placehold.it/500x300', width: '100%', height: '200px'
          .footer
            %h6 Summer Jams With Dj Flex
            %i.fa.fa-user
            Friday Events
            %p
              Every Friday, London
    .col-sm-4
      = link_to event_pictures_path do
        .row.text-center.camera
        .letter
          = image_tag 'http://placehold.it/500x300', width: '100%', height: '200px'
    .col-sm-4
      = link_to event_pictures_path do
        .letter
          = image_tag 'http://placehold.it/500x300', width: '100%', height: '200px'

app/views/eventsvideos/index.haml
.main-layout
  .container
    %h1.text-center
      Events In Videos

app/views/layouts/_categories_menu.haml
.col-md-offset-1
  %nav.navbar.navbar-light
    %div.nav.navbar-nav
      = link_to events_type_path(category: :arts),
              class:"nav-item nav-link btn #{active(events_type_path(category: :arts))}" do
        %small
          .glyphicon.glyphicon-picture
          Arts
      = link_to events_type_path(category: :music),
              class:"nav-item nav-link btn #{active(events_type_path(category: :music))}" do
        %small
          .glyphicon.glyphicon-music
          Music
      = link_to events_type_path(category: :movies),
              class:"nav-item nav-link btn #{active(events_type_path(category: :movies))}" do
        %small
          .glyphicon.glyphicon-film
          Movies
      = link_to events_type_path(category: :nightlife),
              class:"nav-item nav-link btn #{active(events_type_path(category: :nightlife))}" do
        %small
          .glyphicon.glyphicon-play-circle
          Nightlife
      = link_to events_type_path(category: "food & drinks"),
              class:"nav-item nav-link btn #{active(events_type_path(category: 'food & drinks'))}" do
        %small
          .glyphicon.glyphicon-glass
          Food/Drinks
      = link_to events_type_path(category: :festivals),
              class:"nav-item nav-link btn #{active(events_type_path(category: :festivals))}" do
        %small
          .glyphicon.glyphicon-sound-stereo
          Festivals
      = link_to events_type_path(category: :fitness),
              class:"nav-item nav-link btn #{active(events_type_path(category: :fitness))}" do
        %small
          .glyphicon.glyphicon-heart
          Fitness
      = link_to events_type_path(category: :gaming),
              class:"nav-item nav-link btn #{active(events_type_path(category: :gaming))}" do
        %small
          .glyphicon.glyphicon-queen
          Gaming

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    = display_meta_tags site: "beatLyfie"
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-brand
          beatLyfie
        .navbar-header.navbar-right
          = button_tag class: "navbar-toggle collapsed",
            data: { toggle: "collapse", target:"#listings" },
            "aria-expanded" => false do
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .collapse.navbar-collapse#listings
            %ul.nav.navbar-nav
              %li{class: active(root_path)}
                = link_to "Home", root_path
              %li{class: active(event_pictures_path)}
                = link_to "Events In Pictures", event_pictures_path
              %li{class: active(event_video_path)}
                = link_to "Videos", event_video_path
              %li{class: active("#")}
                = link_to "login", "#"

    = yield

    .footer.bg-footer
      .container
        .row
          .col-sm-4
            %h3
              Social Media
            %ul
              %li
                = fa_stacked_icon "facebook", base: "circle", class: "fa-1x"
                Facebook
              %li
                = fa_stacked_icon "twitter", base: "circle", class: "fa-1x"
                Twitter
              %li
                = fa_stacked_icon "instagram", base: "circle", class: "fa-1x"
                Instagram
          .col-sm-4
            %h3
              Why I do This
            %ul
              %li
                When it started
              %li
                Whats next
              %li
                Usage Policy
              %li
                Privacy concerns
          .col-sm-4
            %h3
              Join The Club
            %ul
              %li
                Get Listed
              %li
                Claim your event in Pictures & Videos
              %li
                %h3
                  Subscribe to our newsletters
                .form-group
                  .input-group.input-group-lg
                    = text_field_tag :search,
                    nil,
                    placeholder: "Add your email",
                    class: "form-control"
                    .input-group-btn
                      = link_to "#", class: "btn btn-warning" do
                        .fa.fa-send
    .cpy-note
      beatLyfie
      %span.cpy #{"&copy;".html_safe} #{Time.now.year}

app/views/listings/index.haml
.header
  .container
    .jumbotron.text-center
      %h1.display-3
      %h3.lead
        Search for Events in
      %h2.text-center UK
      .container
        .col-md-offset-2.col-md-8
          .form-group
            .input-group.input-group-lg
              = text_field_tag :search,
              nil,
              placeholder: "Search by a category",
              class: "form-control"
              .input-group-btn
                = link_to "#", class: "btn btn-warning" do
                  .glyphicon.glyphicon-search
        = render('layouts/categories_menu')
      %i.glyphicon.glyphicon-chevron-down

.container.main-listings
  %h1.text-center
    Plans For This Week
  - @events.each do |event|
    .col-md-4.event-box
      = link_to "More Details", event_path(id: event.id, category: "this week"),
          class: "btn-lg btn-more"
      .event-card.well.well-sm
        = image_tag(event.image_url,width: "100%",height: "250px")
        .panel-body
          %h3
            %b= event.title
          .row
            %small
              %i.fa.fa-calendar
              = event.starting_at
          .row
            %small
              %i.fa.fa-map-marker
              = event.name_of_venue
        .footer
          .col-xs-12.pull-right.text-right
            = link_to "#" do
              = fa_stacked_icon "bookmark", base: "circle"
            = link_to "#" do
              = fa_stacked_icon "share-alt", base: "circle"
.in-pictures
  %h1.text-light.text-center
    Checkout Previous Events In Snaps & Clips
  .row
    .col-sm-6
      = link_to event_pictures_path do
        .row.text-center.camera
          %i
            = fa_stacked_icon "camera", base: "circle", class: "fa-3x"
        .letter
          = image_tag 'http://placehold.it/500x300', width: '100%', height: '300px'
    .col-sm-6
      = link_to event_video_path do
        .row.text-center.camera
          %i
            = fa_stacked_icon "video-camera", base: "circle", class: "fa-3x"
        .letter
          = image_tag 'http://placehold.it/500x300', width: '100%', height: '300px'